# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# See http://symfony.com/fr/doc/current/components/yaml/yaml_format.html
# See http://codebeautify.org/yaml-validator

# APPLICATION SETTINGS
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/autobot_singapore?useUnicode=true&amp;charaterEncoding=utf-8
  username: root
  password: newpassword
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1
spring:
    main.show-banner: true
    main.web-environment: false
logging:
    config: ${env}/log4j2.xml